### ISSUE TITLE
Domotica Daemon?

### ISSUE THREAD

**Issue by yorickr** [yorickr/yjmpd#3]
Janco pls.

`
class YjmpdDaemon:
    """A generic domotica deamon class.
    Usage: subclass the domotica deamon class and override the run() method."""
`

[Dit is geen domotica daemon weet je nog? xD ](https://github.com/yorickr/yjmpd/blob/dev/yjmpd/YjmpdDaemon.py#L11)

**Comment by jancoow** [comment]
Fixed in #  409982e
